// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.9.0
// source: usercenter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Usercenter_SendCode_FullMethodName            = "/pb.usercenter/SendCode"
	Usercenter_Register_FullMethodName            = "/pb.usercenter/Register"
	Usercenter_Login_FullMethodName               = "/pb.usercenter/Login"
	Usercenter_FindMemberById_FullMethodName      = "/pb.usercenter/FindMemberById"
	Usercenter_FindAddressByCoinId_FullMethodName = "/pb.usercenter/FindAddressByCoinId"
	Usercenter_WithdrawSendCode_FullMethodName    = "/pb.usercenter/WithdrawSendCode"
	Usercenter_WithdrawCode_FullMethodName        = "/pb.usercenter/WithdrawCode"
	Usercenter_WithdrawRecord_FullMethodName      = "/pb.usercenter/WithdrawRecord"
)

// UsercenterClient is the client API for Usercenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsercenterClient interface {
	SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	FindMemberById(ctx context.Context, in *FindMemberByIdReq, opts ...grpc.CallOption) (*FindMemberByIdResp, error)
	FindAddressByCoinId(ctx context.Context, in *FindAddressByCoinIdReq, opts ...grpc.CallOption) (*FindAddressByCoinIdResp, error)
	WithdrawSendCode(ctx context.Context, in *WithdrawSendCodeReq, opts ...grpc.CallOption) (*WithdrawSendCodeResp, error)
	WithdrawCode(ctx context.Context, in *WithdrawCodeReq, opts ...grpc.CallOption) (*WithdrawCodeResp, error)
	WithdrawRecord(ctx context.Context, in *WithdrawRecordReq, opts ...grpc.CallOption) (*WithdrawRecordResp, error)
}

type usercenterClient struct {
	cc grpc.ClientConnInterface
}

func NewUsercenterClient(cc grpc.ClientConnInterface) UsercenterClient {
	return &usercenterClient{cc}
}

func (c *usercenterClient) SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error) {
	out := new(SendCodeResp)
	err := c.cc.Invoke(ctx, Usercenter_SendCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, Usercenter_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, Usercenter_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) FindMemberById(ctx context.Context, in *FindMemberByIdReq, opts ...grpc.CallOption) (*FindMemberByIdResp, error) {
	out := new(FindMemberByIdResp)
	err := c.cc.Invoke(ctx, Usercenter_FindMemberById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) FindAddressByCoinId(ctx context.Context, in *FindAddressByCoinIdReq, opts ...grpc.CallOption) (*FindAddressByCoinIdResp, error) {
	out := new(FindAddressByCoinIdResp)
	err := c.cc.Invoke(ctx, Usercenter_FindAddressByCoinId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) WithdrawSendCode(ctx context.Context, in *WithdrawSendCodeReq, opts ...grpc.CallOption) (*WithdrawSendCodeResp, error) {
	out := new(WithdrawSendCodeResp)
	err := c.cc.Invoke(ctx, Usercenter_WithdrawSendCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) WithdrawCode(ctx context.Context, in *WithdrawCodeReq, opts ...grpc.CallOption) (*WithdrawCodeResp, error) {
	out := new(WithdrawCodeResp)
	err := c.cc.Invoke(ctx, Usercenter_WithdrawCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usercenterClient) WithdrawRecord(ctx context.Context, in *WithdrawRecordReq, opts ...grpc.CallOption) (*WithdrawRecordResp, error) {
	out := new(WithdrawRecordResp)
	err := c.cc.Invoke(ctx, Usercenter_WithdrawRecord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsercenterServer is the server API for Usercenter service.
// All implementations must embed UnimplementedUsercenterServer
// for forward compatibility
type UsercenterServer interface {
	SendCode(context.Context, *SendCodeReq) (*SendCodeResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	FindMemberById(context.Context, *FindMemberByIdReq) (*FindMemberByIdResp, error)
	FindAddressByCoinId(context.Context, *FindAddressByCoinIdReq) (*FindAddressByCoinIdResp, error)
	WithdrawSendCode(context.Context, *WithdrawSendCodeReq) (*WithdrawSendCodeResp, error)
	WithdrawCode(context.Context, *WithdrawCodeReq) (*WithdrawCodeResp, error)
	WithdrawRecord(context.Context, *WithdrawRecordReq) (*WithdrawRecordResp, error)
	mustEmbedUnimplementedUsercenterServer()
}

// UnimplementedUsercenterServer must be embedded to have forward compatible implementations.
type UnimplementedUsercenterServer struct {
}

func (UnimplementedUsercenterServer) SendCode(context.Context, *SendCodeReq) (*SendCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCode not implemented")
}
func (UnimplementedUsercenterServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUsercenterServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUsercenterServer) FindMemberById(context.Context, *FindMemberByIdReq) (*FindMemberByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMemberById not implemented")
}
func (UnimplementedUsercenterServer) FindAddressByCoinId(context.Context, *FindAddressByCoinIdReq) (*FindAddressByCoinIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAddressByCoinId not implemented")
}
func (UnimplementedUsercenterServer) WithdrawSendCode(context.Context, *WithdrawSendCodeReq) (*WithdrawSendCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawSendCode not implemented")
}
func (UnimplementedUsercenterServer) WithdrawCode(context.Context, *WithdrawCodeReq) (*WithdrawCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawCode not implemented")
}
func (UnimplementedUsercenterServer) WithdrawRecord(context.Context, *WithdrawRecordReq) (*WithdrawRecordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawRecord not implemented")
}
func (UnimplementedUsercenterServer) mustEmbedUnimplementedUsercenterServer() {}

// UnsafeUsercenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsercenterServer will
// result in compilation errors.
type UnsafeUsercenterServer interface {
	mustEmbedUnimplementedUsercenterServer()
}

func RegisterUsercenterServer(s grpc.ServiceRegistrar, srv UsercenterServer) {
	s.RegisterService(&Usercenter_ServiceDesc, srv)
}

func _Usercenter_SendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).SendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_SendCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).SendCode(ctx, req.(*SendCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_FindMemberById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMemberByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).FindMemberById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_FindMemberById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).FindMemberById(ctx, req.(*FindMemberByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_FindAddressByCoinId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAddressByCoinIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).FindAddressByCoinId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_FindAddressByCoinId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).FindAddressByCoinId(ctx, req.(*FindAddressByCoinIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_WithdrawSendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawSendCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).WithdrawSendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_WithdrawSendCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).WithdrawSendCode(ctx, req.(*WithdrawSendCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_WithdrawCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).WithdrawCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_WithdrawCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).WithdrawCode(ctx, req.(*WithdrawCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usercenter_WithdrawRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsercenterServer).WithdrawRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usercenter_WithdrawRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsercenterServer).WithdrawRecord(ctx, req.(*WithdrawRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Usercenter_ServiceDesc is the grpc.ServiceDesc for Usercenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Usercenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.usercenter",
	HandlerType: (*UsercenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCode",
			Handler:    _Usercenter_SendCode_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Usercenter_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Usercenter_Login_Handler,
		},
		{
			MethodName: "FindMemberById",
			Handler:    _Usercenter_FindMemberById_Handler,
		},
		{
			MethodName: "FindAddressByCoinId",
			Handler:    _Usercenter_FindAddressByCoinId_Handler,
		},
		{
			MethodName: "WithdrawSendCode",
			Handler:    _Usercenter_WithdrawSendCode_Handler,
		},
		{
			MethodName: "WithdrawCode",
			Handler:    _Usercenter_WithdrawCode_Handler,
		},
		{
			MethodName: "WithdrawRecord",
			Handler:    _Usercenter_WithdrawRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usercenter.proto",
}
