// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mscoin/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/check/login",
				Handler: CheckLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mobile/code",
				Handler: SendCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register/phone",
				Handler: RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/uc"),
	)
}
