// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"mscoin/app/usercenter/cmd/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/mobile/code",
				Handler: SendCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/uc"),
	)
}
