version: '3'
services:
  etcd01:
    image: bitnami/etcd:3.5.6
    container_name: etcd01
    restart: always
    networks:
      - etcd_cluster_net
    ports:
      - "20000:2379"
      - "20001:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes                                                                   # 允许不用密码登录
      - ETCD_NAME=etcd01                                                                                # etcd 的名字
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd01:2380                                             # 列出这个成员的伙伴 URL 以便通告给集群的其他成员
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380                                                       # 用于监听伙伴通讯的URL列表
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379                                                     # 用于监听客户端通讯的URL列表
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd01:2379                                                   # 列出这个成员的客户端URL，通告给集群中的其他成员
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster                                                         # 在启动期间用于 etcd 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380 # 为启动初始化集群配置
      - ETCD_INITIAL_CLUSTER_STATE=new                                                                  # 初始化集群状态
  etcd02:
    image: bitnami/etcd:3.5.6
    container_name: etcd02
    restart: always
    networks:
      - etcd_cluster_net
    ports:
      - "20002:2379"
      - "20003:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes                                                                  # 允许不用密码登录
      - ETCD_NAME=etcd02                                                                               # etcd 的名字
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd02:2380                                            # 列出这个成员的伙伴 URL 以便通告给集群的其他成员
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380                                                      # 用于监听伙伴通讯的URL列表
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379                                                    # 用于监听客户端通讯的URL列表
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd02:2379                                                  # 列出这个成员的客户端URL，通告给集群中的其他成员
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster                                                        # 在启动期间用于 etcd 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380 # 为启动初始化集群配置
      - ETCD_INITIAL_CLUSTER_STATE=new                                                                 # 初始化集群状态
  etcd03:
    image: bitnami/etcd:3.5.6
    container_name: etcd03
    restart: always
    networks:
      - etcd_cluster_net
    ports:
      - "20004:2379"
      - "20005:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes                                                                  # 允许不用密码登录
      - ETCD_NAME=etcd03                                                                               # etcd 的名字
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd03:2380                                            # 列出这个成员的伙伴 URL 以便通告给集群的其他成员
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380                                                      # 用于监听伙伴通讯的URL列表
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379                                                    # 用于监听客户端通讯的URL列表
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd03:2379                                                  # 列出这个成员的客户端URL，通告给集群中的其他成员
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster                                                        # 在启动期间用于 etcd 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380 # 为启动初始化集群配置
      - ETCD_INITIAL_CLUSTER_STATE=new                                                                 # 初始化集群状态
networks:
  etcd_cluster_net:
    # external: 外部的. 使用docker network create创建好的网络, 名字就是zk_kafka_cluster_net
    external: true
