// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"

	"mscoin/app/usercenter/cmd/rpc/internal/logic"
	"mscoin/app/usercenter/cmd/rpc/internal/svc"
	"mscoin/app/usercenter/cmd/rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) SendCode(ctx context.Context, in *pb.SendCodeReq) (*pb.SendCodeResp, error) {
	l := logic.NewSendCodeLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}

func (s *UsercenterServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UsercenterServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UsercenterServer) FindMemberById(ctx context.Context, in *pb.FindMemberByIdReq) (*pb.FindMemberByIdResp, error) {
	l := logic.NewFindMemberByIdLogic(ctx, s.svcCtx)
	return l.FindMemberById(in)
}

func (s *UsercenterServer) FindAddressByCoinId(ctx context.Context, in *pb.FindAddressByCoinIdReq) (*pb.FindAddressByCoinIdResp, error) {
	l := logic.NewFindAddressByCoinIdLogic(ctx, s.svcCtx)
	return l.FindAddressByCoinId(in)
}

func (s *UsercenterServer) WithdrawSendCode(ctx context.Context, in *pb.WithdrawSendCodeReq) (*pb.WithdrawSendCodeResp, error) {
	l := logic.NewWithdrawSendCodeLogic(ctx, s.svcCtx)
	return l.WithdrawSendCode(in)
}

func (s *UsercenterServer) WithdrawCode(ctx context.Context, in *pb.WithdrawCodeReq) (*pb.WithdrawCodeResp, error) {
	l := logic.NewWithdrawCodeLogic(ctx, s.svcCtx)
	return l.WithdrawCode(in)
}

func (s *UsercenterServer) WithdrawRecord(ctx context.Context, in *pb.WithdrawRecordReq) (*pb.WithdrawRecordResp, error) {
	l := logic.NewWithdrawRecordLogic(ctx, s.svcCtx)
	return l.WithdrawRecord(in)
}
