// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Phone   string `json:"phone"`
	Country string `json:"country"`
}

type RegisterResp struct {
}

type SendCodeReq struct {
	Phone   string `json:"phone"`
	Country string `json:"country"`
}

type SendCodeResp struct {
}
